
version: '3.1'
services:  
  siteadmin:
    image: siteadmin
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: yugabyte
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5433
      DATABASE_USERNAME: yugabyte
      DATABASE_PASSWORD: yugabyte
    ports:
      - '1337:1337'